flashcard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('novo_flashcard/', views.novo_flashcard, name='novo_flashcard'),
    path('deletar_flashcard/<int:id>', views.deletar_flashcard, name='deletar_flashcard'),
    path('iniciar_desafio/', views.iniciar_desafio, name='iniciar_desafio'),
    path('listar_desafio/', views.listar_desafio, name='listar_desafio'),
    path('desafio/<int:id>/', views.desafio, name='desafio'),
    path('responder_flashcard/<int:id>/', views.responder_flashcard, name='responder_flashcard'),
    path('relatorio/<int:id>/', views.relatorio, name='relatorio')
]

study_async/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('flashcard/', include('flashcard.urls')),
    path('apostilas/', include('apostilas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout')
]

flashcard/models.py
from django.contrib.auth.models import User
from django.db import models


class Categoria(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome


class Flashcard(models.Model):
    DIFICULDADE_CHOICES = (('D', 'Difícil'), ('M', 'Médio'), ('F', 'Fácil'))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    pergunta = models.CharField(max_length=100)
    resposta = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    dificuldade = models.CharField(max_length=1, choices=DIFICULDADE_CHOICES)

    def __str__(self):
        return self.pergunta

    @property
    def css_dificuldade(self):
        if self.dificuldade == 'F':
            return 'flashcard-facil'
        elif self.dificuldade == 'M':
            return 'flashcard-medio'
        elif self.dificuldade == 'D':
            return 'flashcard-dificil'


class FlashcardDesafio(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.DO_NOTHING)
    respondido = models.BooleanField(default=False)
    acertou = models.BooleanField(default=False)

    def __str__(self):
        return self.flashcard.pergunta


class Desafio(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=100)
    categoria = models.ManyToManyField(Categoria)
    quantidade_perguntas = models.IntegerField()
    dificuldade = models.CharField(
        max_length=1, choices=Flashcard.DIFICULDADE_CHOICES
    )
    flashcards = models.ManyToManyField(FlashcardDesafio)

    def __str__(self):
        return self.titulo

flashcard/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.messages import constants
from django.contrib import messages

from .models import Categoria, Flashcard, Desafio, FlashcardDesafio


def novo_flashcard(request):
    if not request.user.is_authenticated:
        return redirect('login')

    if request.method == 'GET':
        categorias = Categoria.objects.all()
        dificuldades = Flashcard.DIFICULDADE_CHOICES
        flashcards = Flashcard.objects.filter(user=request.user)

        categoria_filtro = request.GET.get('categoria')
        dificuldade_filtro = request.GET.get('dificuldade')

        if categoria_filtro:
            flashcards = flashcards.filter(categoria__id=categoria_filtro)

        if dificuldade_filtro:
            flashcards = flashcards.filter(dificuldade=dificuldade_filtro)

        return render(
            request,
            'novo_flashcard.html',
            {
                'categorias': categorias,
                'dificuldades': dificuldades,
                'flashcards': flashcards,
            }

        )
    elif request.method == 'POST':
        pergunta = request.POST.get('pergunta')
        resposta = request.POST.get('resposta')
        categoria = request.POST.get('categoria')
        dificuldade = request.POST.get('dificuldade')

        if len(pergunta.strip()) == 0 or len(resposta.strip()) == 0:
            messages.add_message(
                request,
                constants.ERROR,
                'Preencha os campos de pergunta e resposta'
            )
            return redirect('novo_flashcard')

        flashcard = Flashcard(
            user=request.user,
            pergunta=pergunta,
            resposta=resposta,
            categoria_id=categoria,
            dificuldade=dificuldade,
        )

        flashcard.save()

        messages.add_message(
            request, constants.SUCCESS, 'Flashcard criado com suceso!!'
        )

        return redirect('novo_flashcard')


def deletar_flashcard(request, id):
    # validar a segurança
    flashcard = Flashcard.objects.get(id=id)
    flashcard.delete()
    messages.add_message(
        request,
        constants.SUCCESS,
        'Flashcard deletado com sucesso!!'
    )

    return redirect('novo_flashcard')


def iniciar_desafio(request):
    if request.method == 'GET':
        categorias = Categoria.objects.all()
        dificuldades = Flashcard.DIFICULDADE_CHOICES

        return render(
            request,
            'iniciar_desafio.html',
            {
                'categorias': categorias,
                'dificuldades': dificuldades
            },
        )

    elif request.method == 'POST':
        titulo = request.POST.get('titulo')
        categorias = request.POST.getlist('categorias')
        dificuldade = request.POST.get('dificuldade')
        qtd_perguntas = request.POST.get('qtd_perguntas')

        desafio = Desafio(
            user=request.user,
            titulo=titulo,
            quantidade_perguntas=qtd_perguntas,
            dificuldade=dificuldade,
        )

        desafio.save()

        desafio.categoria.add(*categorias)

        flashcards = (
            Flashcard.objects.filter(user=request.user)
            .filter(dificuldade=dificuldade)
            .filter(categoria_id__in=categorias)
            .order_by('?')
        )

        if flashcards.count() < int(qtd_perguntas):
            return redirect('/flashcard/iniciar_desafio')

        flashcards = flashcards[: int(qtd_perguntas)]

        for f in flashcards:
            flashcard_desafio = FlashcardDesafio(
                flashcard=f,
            )

            flashcard_desafio.save()
            desafio.flashcards.add(flashcard_desafio)

        desafio.save()

        return redirect(f'/flashcard/listar_desafio')


def listar_desafio(request):
    desafios = Desafio.objects.filter(user=request.user)
    # TODO: desenvolver os status
    # TODO: desenvolver os filtros
    return render(
        request,
        'listar_desafio.html',
        {
            'desafios': desafios,
        },
    )


def desafio(request, id):
    desafio = Desafio.objects.get(id=id)

    if not desafio.user == request.user:
        raise Http404()

    if request.method == 'GET':
        acertos = desafio.flashcards.filter(respondido=True).filter(acertou=True).count()
        errados = desafio.flashcards.filter(respondido=True).filter(acertou=False).count()
        faltantes = desafio.flashcards.filter(respondido=False).count()

        return render(
            request,
            'desafio.html',
            {
                'desafio': desafio,
                'acertos': acertos,
                'errados': errados,
                'faltantes': faltantes,
             }
        )


def responder_flashcard(request, id):
    flashcard_desafio = FlashcardDesafio.objects.get(id=id)
    acertou = request.GET.get('acertou')
    desafio_id = request.GET.get('desafio_id')

    if not flashcard_desafio.flashcard.user == request.user:
        raise Http404()

    flashcard_desafio.respondido = True
    flashcard_desafio.acertou = True if acertou == '1' else False
    flashcard_desafio.save()

    return redirect(f'/flashcard/desafio/{desafio_id}/')


def relatorio(request, id):
    desafio = Desafio.objects.get(id=id)

    acertos = desafio.flashcard.filter(acertou=True).count()
    errados = desafio.flashcard.filter(acertou=False).count()

    dados = [acertos, errados]

    categorias = desafio.categoria.all()
    nome_categoria = [i.nome for i in categorias]

    data = []

    for categoria in categorias:
        data.append(desafio.flashcard.filter(flashcard__categoria=categoria).filter(acertou=True).count())

    return render(
        request,
        'relatorio.html',
        {
            'desafio': desafio,
            'dados': dados,
            'categorias': nome_categoria,
            'data': data,
        }
    )

flashcard/templates/desafio.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'css/usuarios/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/desafio.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}


{% block 'conteudo' %}

    {% include 'parciais/cabecalho.html' %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <h3 class="fonte-secundaria" >Desafio iniciado</h3>
                <span class="badge-categoria">Programação</span>
                <span class="badge-categoria" >Matemática</span>
                <br>
                <br>
                <br>
                {% for flash in desafio.flashcards.all %}
                    <div class="box-new-flashcard {% if flash.respondido %}op2{% endif %}">
                        <div class="flashcard {{ flash.flashcard.css_dificuldade }}">

                            <div class="flashcard-categoria">
                                {{flash.flashcard.categoria}}
                            </div>
                            <br>
                            <br>
                            <div class="flashcard-box-item" onclick="flip_card({{flash.id}})">
                                <p class="flashcard-item">{{flash.flashcard.pergunta}}</p>
                            </div>

                            {% if not flash.respondido %}
                                <div class="responder">

                                    <a href="{% url 'responder_flashcard' flash.id %}?acertou=0&desafio_id={{desafio.id}}"><i class='bx bxs-x-square icone-vermelho'></i></a>
                                    <a href="{% url 'responder_flashcard' flash.id %}?acertou=1&desafio_id={{desafio.id}}"><i class='bx bxs-check-square icone-verde' ></i></a>
                                </div>
                            {% else %}
                                {% if flash.acertou %}
                                    <span class="badge bg-success">Acertou</span>
                                {% else %}
                                    <span class="badge bg-danger">Errou</span>
                                {% endif%}

                            {% endif %}

                        </div>
                        <div class="resposta-flashcard" id="{{flash.id}}">
                            {{flash.flashcard.resposta}}
                        </div>
                    </div>
                    <br>
                    <br>
                {% endfor %}

            </div>
            <div class="col-md">

                <h3 class="fonte-secundaria">Resultado</h3>
                <p class="fonte-p">Acertos: {{ acertos }}</p>
                <p class="fonte-p">Erros: {{ errados }}</p>
                <p class="fonte-p">Faltantes: {{ faltantes }}</p>
                <br>
                <a class="btn-cadastro btn-desafio" href="{% url 'relatorio' desafio.id %}">Relatório detalhado</a>
            </div>
        </div>

    </div>
    <script src="{% static 'js/flashcard/flashcard.js' %}"></script>
{% endblock 'conteudo' %}

flashcard/templates/iniciar_desafio.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'css/usuarios/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/iniciar_desafio.css' %}" rel="stylesheet">

{% endblock 'cabecalho' %}


{% block 'conteudo' %}

    {% include 'parciais/cabecalho.html' %}
    <div class="container ctx">
        <br>
        <br>
        <h2 class="fonte-principal">Iniciar desafio</h2>
        <p class="fonte-secundaria">Escolha as categorias e a dificuldade do desafio</p>
        <div class="row">

            <div class="col-md">
                <form action="{% url 'iniciar_desafio' %}" method="POST">
                    {% csrf_token%}
                    <label for="">Titulo</label>
                    <input type="text" class="form-control" name="titulo">
            </div>
            <div class="col-md">
                <label>Categoria</label>
                <select name="categoria" class="form-select" multiple>
                    {% for categoria in categorias %}
                        <option value="{{categoria.id}}">
                            {{categoria.nome}}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <label>Dificuldade</label>
                <select name="dificuldade" class="form-select">
                    {% for dificuldade in dificuldades %}
                        <option value="{{dificuldade.0}}">
                            {{dificuldade.1}}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-md">
                <label>Qtd questões</label>
                <input type="number" class="form-control" name="qtd_perguntas">
            </div>

        </div>
        <br>
        <br>
        <input type="submit" class="btn-cadastro" value="Iniciar desafio">
        </form>
    </div>
{% endblock 'conteudo' %}

flashcard/templates/listar_desafio.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'css/usuarios/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/desafio.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}


{% block 'conteudo' %}

    {% include 'parciais/cabecalho.html' %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <form action="" method="GET">
                    <label for="">Categoria</label>
                    <select name="categoria" class="form-select">

                    </select>
                </form>
            </div>
            <div class="col-md">
                <label for="">Dificuldade</label>
                <select name="dificuldade" class="form-select">

                </select>
            </div>
            <div class="col-md">
                <br>
                <input type="submit" value="Filtrar" class="btn-cadastro">
                </form>
            </div>
        </div>
        <br>
        <br>
        <div class="box-listar">
            <table>
                <thead>
                <tr>
                    <th scope="col">Desafio</th>
                    <th scope="col">Titulo</th>
                    <th scope="col">Dificuldade</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                    {% for desafio in desafios %}
                        <tr class="linha">
                            <th><a href="{% url 'desafio' desafio.id %}">{{desafio.id}}</a></th>
                            <td>{{desafio.titulo}}</td>
                            <td>{{desafio.get_dificuldade_display}}</td>
                            <td>{{desafio.status}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script src="{% static 'js/flashcard/flashcard.js' %}"></script>
{% endblock 'conteudo' %}

flashcard/templates/novo_flashcard.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}
    <link href="{% static 'css/usuarios/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/novo_flashcard.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}

{% block 'conteudo' %}

    {% include 'parciais/cabecalho.html' %}

    <div class="container">
        <br>
        <br>
        <div class="row">

            <div class="col-md">

                <div class="box-form">
                    <form action="{% url 'novo_flashcard' %}" method="POST">
                        {% csrf_token %}
                        <h3>Novo flashcard</h3>
                        {% if messages %}
                            <br>
                            {% for message in messages %}
                                <section class="alert {{message.tags}}">
                                    {{message}}
                                </section>
                            {% endfor %}
                        {% endif %}
                        <br>
                        <label>Pergunta</label>
                        <input type="text" class="form-control" placeholder="pergunta" name="pergunta">
                        <br>
                        <label>Resposta</label>
                        <textarea class="form-control" name="resposta"></textarea>
                        <br>
                        <div class="row">

                            <div class="col-md">
                                <label for="">Categoria</label>
                                <select class="form-select" name="categoria">
                                    {% for categoria in categorias %}
                                        <option value="{{categoria.id}}">{{categoria.nome}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md">
                                <label for="">Dificuldade</label>
                                <select class="form-select" name="dificuldade">
                                    {% for dificuldade in dificuldades %}
                                        <option value="{{dificuldade.0}}">{{dificuldade.1}}</option>
                                    {% endfor %}
                                </select>

                            </div>

                        </div>
                        <br>
                        <input type="submit" value="Enviar" class="btn-cadastro">
                        <br>
                        <br>
                        <br>
                    </form>
                </div>

            </div>
            <div class="col-md">
                <form action="{% url 'novo_flashcard' %}" method="GET">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md">
                            <label for="">Categoria</label>
                            <select name="categoria" id="" class="form-select">
                                <option value="">Todas as Categorias</option>
                                {% for categoria in categorias %}
                                    <option value="{{categoria.id}}">{{categoria.nome}}</option>
                                {% endfor %}

                            </select>
                        </div>
                        <div class="col-md">
                            <label for="">Dificuldade</label>
                            <select name="dificuldade" id="" class="form-select">
                                <option value="">Todas as Dificuldades</option>
                                {% for dificuldade in dificuldades %}
                                    <option value="{{dificuldade.0}}">{{dificuldade.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md">
                            <br>
                            <input type="submit" style="width: 100%" value="Filtrar" class="btn-cadastro">
                        </div>
                    </div>

                </form>

                <br>
                <br>

                {% for flash in flashcards %}
                    <div class="box-new-flashcard" onclick="flip_card({{ flash.id }})">
                        <div class="flashcard">

                            <div class="flashcard-categoria">
                                {{flash.categoria}}
                            </div>

                            <a href="{% url 'deletar_flashcard' flash.id %}"><i class='icone-exit bx bx-x-circle'></i></a>
                            <br>
                            <br>
                            <div class="flashcard-box-item">
                                <p class="flashcard-item">{{flash.pergunta}}</p>
                            </div>

                        </div>
                        <div class="resposta-flashcard" id="{{ flash.id }}">
                            {{flash.resposta}}
                        </div>
                    </div>
                    <br>
                    <br>
                {% endfor %}
                <br>
                <br>


            </div>
        </div>
    </div>

    <script src="{% static 'js/flashcard/flashcard.js' %}">

    </script>

{% endblock 'conteudo' %}

flashcard/templates/relatorio.html
{% extends "base.html" %}
{% load static %}

{% block 'cabecalho' %}

    <link href="{% static 'css/usuarios/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'css/flashcard/desafio.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'cabecalho' %}


{% block 'conteudo' %}
    {% include "parciais/cabecalho.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <p class="fonte-secundaria">{{desafio.titulo}}</p>
                <hr>
                <canvas id="grafico1"></canvas>
            </div>
            <div class="col-md">
                <br><br><br><br>
                
                <div style="background-color: white;">

                    <canvas id="grafico2"></canvas>

                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"/>
    <script>
        const ctx = document.getElementById('grafico1');

        new Chart(ctx, {
            type: 'pie',
            data: {
                labels: [
                    'Acertos',
                    'Erros'
                ],
                datasets: [{
                    label: 'Qtd',
                    data: {{ dados }},
                    borderWidth:1
                }]
            },
        });
    </script>
    <script>
        const ctx2 = document.getElementById('grafico2');

        new Chart(ctx2, {
           type: 'radar',
           data: {
               labels: {{ categorias|safe }},
               datasets: [{
                   label: 'Qtd',
                   data: {{ data }},
                   borderWidth: 1,
                   fill: true,
                   backgroundColor: 'rgba(255,99,132,0.2)',
                   borderColor: 'rgba(255,99,132)',
                   pointBackgroundColor: 'rgba(255,99,132)',
                   pointBorderColor: '#fff',
                   pointHoverBackgroundColor: '#fff',
                   pointHoverBorderColor: 'rgba(255,99,132)',

               }]
           }
        });
    </script>

{% endblock 'conteudo' %}